import socket
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(('localhost', 8000))
server_socket.listen(1)
print("Server is waiting for a connection...")
conn, addr = server_socket.accept()
print(f"Connected by {addr}")
conn.send("Hello from the server!".encode())
data = conn.recv(1024)
print(f"Received from client: {data.decode()}")
conn.close()
server_socket.close()